modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''${mod_description}'''
authors = "${mod_author}"
logoFile = "logo.png"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true

[[dependencies.${mod_id}]]
modId = "ftbultimine"
mandatory = true
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "shouldersurfing"
mandatory = true
ordering = "NONE"
side = "CLIENT"