modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''${mod_description}'''
authors = "${mod_author}"
logoFile = "logo.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${deps_neoforge_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${deps_minecraft_range}"

[[dependencies.${mod_id}]]
modId = "ftbultimine"
type = "required"
reason = "integration"
versionRange = "${deps_ftbultimine_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "shouldersurfing"
type = "required"
reason = "integration"
versionRange = "${deps_shouldersurfing_range}"
ordering = "NONE"
side = "CLIENT"